

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    #layout: BaseLayout

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:<password>@cluster0.vigqsrv.mongodb.net/?retryWrites=true&w=majority
      database: task

  jpa:
    show-sql: true